name: build-test-manylinux-aarch64

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-wheel:
    name: Build and test Semgrep python wheel
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        architecture:
          - x86_64
          - aarch64
    steps:
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: depot/setup-action@v1
      - name: Build and test python wheel
        id: build-semgrep-wheel
        uses: depot/build-push-action@v1.8.0
        with:
          project: fhmxj6w9z8
          platforms: linux/${{ matrix.architecture }}
          outputs: type=docker,dest=/tmp/image.tar
          target: semgrep-wheel
          buildx-fallback: true
          build-args: |
            WHEEL_ARCH=${{ matrix.architecture }}
      - name: Extract wheel from docker image
        run: |
          docker load --input /tmp/image.tar
          docker run --platform linux/${{ matrix.architecture }} --rm ${{ steps.build-semgrep-wheel.outputs.imageid }} cat cli/dist.zip > /tmp/dist.zip
      - uses: actions/upload-artifact@v3
        with:
          name: manylinux-${{ matrix.architecture }}-wheel
          path: /tmp/dist.zip
